/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdditionalWorkRecord {
  'id' : bigint,
  'workType' : string,
  'employeeName' : string,
  'pcsDone' : number,
  'date' : string,
  'color' : string,
  'size' : string,
  'ratePerPcs' : number,
  'articleNo' : string,
  'totalAmount' : number,
}
export interface DispatchRecord {
  'id' : bigint,
  'dispatchDate' : string,
  'dispatchPcs' : number,
  'finalPayment' : number,
  'articleNo' : string,
  'sizeWiseBreakup' : string,
  'salePrice' : number,
  'partyName' : string,
  'percentage' : number,
  'colorWiseBreakup' : string,
}
export interface FabricConsumptionReport {
  'fabricPerPiece' : number,
  'articleNo' : string,
  'totalCutting' : number,
  'totalFabricUsed' : number,
}
export interface FinishedStockSummary {
  'totalProduced' : number,
  'totalDispatched' : number,
  'available' : number,
  'articleNo' : string,
}
export interface ItemMaster {
  'id' : bigint,
  'size3XL' : number,
  'size4XL' : number,
  'size5XL' : number,
  'sizeXXL' : number,
  'hasAdditionalWork' : boolean,
  'sizeL' : number,
  'sizeM' : number,
  'sizeS' : number,
  'articleNo' : string,
  'sizeXL' : number,
  'sizeXS' : number,
  'colors' : string,
  'workTypes' : string,
  'colorSizeData' : string,
  'totalQuantity' : number,
}
export interface OverlockRecord {
  'id' : bigint,
  'finalAmount' : number,
  'employeeName' : string,
  'pcsRate' : number,
  'date' : string,
  'size' : string,
  'articleNo' : string,
  'quantity' : number,
}
export interface ProductionMismatch {
  'cuttingQty' : number,
  'dispatchedQty' : number,
  'articleNo' : string,
  'stitchedQty' : number,
}
export interface ProductionRecord {
  'id' : bigint,
  'finalAmount' : number,
  'dispatchedPcs' : number,
  'date' : string,
  'rate' : number,
  'totalPcs' : number,
  'articleNo' : string,
  'cutByMaster' : number,
  'partyName' : string,
  'percentage' : number,
}
export interface TailorRecord {
  'id' : bigint,
  'pcsGiven' : number,
  'date' : string,
  'tailorName' : string,
  'color' : string,
  'tailorRate' : number,
  'size' : string,
  'articleNo' : string,
  'tailorAmount' : number,
}
export interface _SERVICE {
  'addAdditionalWorkRecord' : ActorMethod<
    [string, string, string, string, number, number, string, string],
    bigint
  >,
  'addDispatchRecord' : ActorMethod<
    [string, string, string, number, number, number, string, string],
    bigint
  >,
  'addItemMaster' : ActorMethod<
    [
      string,
      number,
      string,
      boolean,
      string,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      string,
    ],
    bigint
  >,
  'addOverlockRecord' : ActorMethod<
    [string, string, string, string, number, number, number],
    bigint
  >,
  'addProductionRecord' : ActorMethod<
    [string, string, string, number, number, number, number, number, number],
    bigint
  >,
  'addTailorRecord' : ActorMethod<
    [string, string, string, number, number, number, string, string],
    bigint
  >,
  'deleteAdditionalWorkRecord' : ActorMethod<[bigint], boolean>,
  'deleteDispatchRecord' : ActorMethod<[bigint], boolean>,
  'deleteItemMaster' : ActorMethod<[bigint], boolean>,
  'deleteOverlockRecord' : ActorMethod<[bigint], boolean>,
  'deleteProductionRecord' : ActorMethod<[bigint], boolean>,
  'deleteTailorRecord' : ActorMethod<[bigint], boolean>,
  'getAdditionalWorkByArticle' : ActorMethod<
    [string],
    Array<AdditionalWorkRecord>
  >,
  'getAdditionalWorkQtyByColorSize' : ActorMethod<
    [string, string, string],
    number
  >,
  'getAdditionalWorkRecords' : ActorMethod<[], Array<AdditionalWorkRecord>>,
  'getArticleRemainingQty' : ActorMethod<[string], [] | [number]>,
  'getArticleReport' : ActorMethod<[], Array<[string, number]>>,
  'getAvailableStock' : ActorMethod<[string], number>,
  'getDispatchRecords' : ActorMethod<[], Array<DispatchRecord>>,
  'getDispatchedQtyByArticle' : ActorMethod<[string], number>,
  'getFabricConsumptionReport' : ActorMethod<
    [],
    Array<FabricConsumptionReport>
  >,
  'getFabricPerPiece' : ActorMethod<[string], number>,
  'getFinishedStockSummary' : ActorMethod<[], Array<FinishedStockSummary>>,
  'getItemMasterByArticle' : ActorMethod<[string], [] | [ItemMaster]>,
  'getItemMasters' : ActorMethod<[], Array<ItemMaster>>,
  'getMasterNames' : ActorMethod<[], Array<string>>,
  'getMasterReport' : ActorMethod<[], Array<[string, number, number]>>,
  'getOverlockRecords' : ActorMethod<[], Array<OverlockRecord>>,
  'getOverlockReport' : ActorMethod<[], Array<[string, number, number]>>,
  'getPaymentSummary' : ActorMethod<[], Array<[string, number, number]>>,
  'getProductionMismatches' : ActorMethod<[], Array<ProductionMismatch>>,
  'getProductionRecords' : ActorMethod<[], Array<ProductionRecord>>,
  'getStitchedQtyByColorSize' : ActorMethod<[string, string, string], number>,
  'getTailorQtyByArticle' : ActorMethod<[string], number>,
  'getTailorRecords' : ActorMethod<[], Array<TailorRecord>>,
  'getTailorReport' : ActorMethod<[], Array<[string, number, number]>>,
  'setFabricPerPiece' : ActorMethod<[string, number], undefined>,
  'updateAdditionalWorkRecord' : ActorMethod<
    [bigint, string, string, string, string, number, number, string, string],
    boolean
  >,
  'updateDispatchRecord' : ActorMethod<
    [bigint, string, string, string, number, number, number, string, string],
    boolean
  >,
  'updateItemMaster' : ActorMethod<
    [
      bigint,
      string,
      number,
      string,
      boolean,
      string,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      string,
    ],
    boolean
  >,
  'updateOverlockRecord' : ActorMethod<
    [bigint, string, string, string, string, number, number, number],
    boolean
  >,
  'updateProductionRecord' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      number,
      number,
      number,
      number,
      number,
      number,
    ],
    boolean
  >,
  'updateTailorRecord' : ActorMethod<
    [bigint, string, string, string, number, number, number, string, string],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];