/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProductionMismatch {
    cuttingQty: number;
    dispatchedQty: number;
    articleNo: string;
    stitchedQty: number;
}
export interface FabricConsumptionReport {
    fabricPerPiece: number;
    articleNo: string;
    totalCutting: number;
    totalFabricUsed: number;
}
export interface DispatchRecord {
    id: bigint;
    dispatchDate: string;
    dispatchPcs: number;
    finalPayment: number;
    articleNo: string;
    sizeWiseBreakup: string;
    salePrice: number;
    partyName: string;
    percentage: number;
    colorWiseBreakup: string;
}
export interface OverlockRecord {
    id: bigint;
    finalAmount: number;
    employeeName: string;
    pcsRate: number;
    date: string;
    size: string;
    articleNo: string;
    quantity: number;
}
export interface FinishedStockSummary {
    totalProduced: number;
    totalDispatched: number;
    available: number;
    articleNo: string;
}
export interface AdditionalWorkRecord {
    id: bigint;
    workType: string;
    employeeName: string;
    pcsDone: number;
    date: string;
    color: string;
    size: string;
    ratePerPcs: number;
    articleNo: string;
    totalAmount: number;
}
export interface ProductionRecord {
    id: bigint;
    finalAmount: number;
    dispatchedPcs: number;
    date: string;
    rate: number;
    totalPcs: number;
    articleNo: string;
    cutByMaster: number;
    partyName: string;
    percentage: number;
}
export interface TailorRecord {
    id: bigint;
    pcsGiven: number;
    date: string;
    tailorName: string;
    color: string;
    tailorRate: number;
    size: string;
    articleNo: string;
    tailorAmount: number;
}
export interface ItemMaster {
    id: bigint;
    size3XL: number;
    size4XL: number;
    size5XL: number;
    sizeXXL: number;
    hasAdditionalWork: boolean;
    sizeL: number;
    sizeM: number;
    sizeS: number;
    articleNo: string;
    sizeXL: number;
    sizeXS: number;
    colors: string;
    workTypes: string;
    colorSizeData: string;
    totalQuantity: number;
}
export interface backendInterface {
    addAdditionalWorkRecord(date: string, articleNo: string, workType: string, employeeName: string, pcsDone: number, ratePerPcs: number, color: string, size: string): Promise<bigint>;
    addDispatchRecord(articleNo: string, partyName: string, dispatchDate: string, dispatchPcs: number, salePrice: number, percentage: number, sizeWiseBreakup: string, colorWiseBreakup: string): Promise<bigint>;
    addItemMaster(articleNo: string, totalQuantity: number, colors: string, hasAdditionalWork: boolean, workTypes: string, sizeXS: number, sizeS: number, sizeM: number, sizeL: number, sizeXL: number, sizeXXL: number, size3XL: number, size4XL: number, size5XL: number, colorSizeData: string): Promise<bigint>;
    addOverlockRecord(date: string, articleNo: string, employeeName: string, size: string, quantity: number, pcsRate: number, finalAmount: number): Promise<bigint>;
    addProductionRecord(date: string, articleNo: string, partyName: string, dispatchedPcs: number, cutByMaster: number, rate: number, percentage: number, totalPcs: number, finalAmount: number): Promise<bigint>;
    addTailorRecord(date: string, articleNo: string, tailorName: string, pcsGiven: number, tailorRate: number, tailorAmount: number, color: string, size: string): Promise<bigint>;
    deleteAdditionalWorkRecord(id: bigint): Promise<boolean>;
    deleteDispatchRecord(id: bigint): Promise<boolean>;
    deleteItemMaster(id: bigint): Promise<boolean>;
    deleteOverlockRecord(id: bigint): Promise<boolean>;
    deleteProductionRecord(id: bigint): Promise<boolean>;
    deleteTailorRecord(id: bigint): Promise<boolean>;
    getAdditionalWorkByArticle(articleNo: string): Promise<Array<AdditionalWorkRecord>>;
    getAdditionalWorkQtyByColorSize(articleNo: string, color: string, size: string): Promise<number>;
    getAdditionalWorkRecords(): Promise<Array<AdditionalWorkRecord>>;
    getArticleRemainingQty(articleNo: string): Promise<number | null>;
    getArticleReport(): Promise<Array<[string, number]>>;
    getAvailableStock(articleNo: string): Promise<number>;
    getDispatchRecords(): Promise<Array<DispatchRecord>>;
    getDispatchedQtyByArticle(articleNo: string): Promise<number>;
    getFabricConsumptionReport(): Promise<Array<FabricConsumptionReport>>;
    getFabricPerPiece(articleNo: string): Promise<number>;
    getFinishedStockSummary(): Promise<Array<FinishedStockSummary>>;
    getItemMasterByArticle(articleNo: string): Promise<ItemMaster | null>;
    getItemMasters(): Promise<Array<ItemMaster>>;
    getMasterNames(): Promise<Array<string>>;
    getMasterReport(): Promise<Array<[string, number, number]>>;
    getOverlockRecords(): Promise<Array<OverlockRecord>>;
    getOverlockReport(): Promise<Array<[string, number, number]>>;
    getPaymentSummary(): Promise<Array<[string, number, number]>>;
    getProductionMismatches(): Promise<Array<ProductionMismatch>>;
    getProductionRecords(): Promise<Array<ProductionRecord>>;
    getStitchedQtyByColorSize(articleNo: string, color: string, size: string): Promise<number>;
    getTailorQtyByArticle(articleNo: string): Promise<number>;
    getTailorRecords(): Promise<Array<TailorRecord>>;
    getTailorReport(): Promise<Array<[string, number, number]>>;
    setFabricPerPiece(articleNo: string, fabricPerPiece: number): Promise<void>;
    updateAdditionalWorkRecord(id: bigint, date: string, articleNo: string, workType: string, employeeName: string, pcsDone: number, ratePerPcs: number, color: string, size: string): Promise<boolean>;
    updateDispatchRecord(id: bigint, articleNo: string, partyName: string, dispatchDate: string, dispatchPcs: number, salePrice: number, percentage: number, sizeWiseBreakup: string, colorWiseBreakup: string): Promise<boolean>;
    updateItemMaster(id: bigint, articleNo: string, totalQuantity: number, colors: string, hasAdditionalWork: boolean, workTypes: string, sizeXS: number, sizeS: number, sizeM: number, sizeL: number, sizeXL: number, sizeXXL: number, size3XL: number, size4XL: number, size5XL: number, colorSizeData: string): Promise<boolean>;
    updateOverlockRecord(id: bigint, date: string, articleNo: string, employeeName: string, size: string, quantity: number, pcsRate: number, finalAmount: number): Promise<boolean>;
    updateProductionRecord(id: bigint, date: string, articleNo: string, partyName: string, dispatchedPcs: number, cutByMaster: number, rate: number, percentage: number, totalPcs: number, finalAmount: number): Promise<boolean>;
    updateTailorRecord(id: bigint, date: string, articleNo: string, tailorName: string, pcsGiven: number, tailorRate: number, tailorAmount: number, color: string, size: string): Promise<boolean>;
}
import type { ItemMaster as _ItemMaster } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAdditionalWorkRecord(arg0: string, arg1: string, arg2: string, arg3: string, arg4: number, arg5: number, arg6: string, arg7: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdditionalWorkRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdditionalWorkRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async addDispatchRecord(arg0: string, arg1: string, arg2: string, arg3: number, arg4: number, arg5: number, arg6: string, arg7: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDispatchRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDispatchRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async addItemMaster(arg0: string, arg1: number, arg2: string, arg3: boolean, arg4: string, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: number, arg12: number, arg13: number, arg14: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addItemMaster(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addItemMaster(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
            return result;
        }
    }
    async addOverlockRecord(arg0: string, arg1: string, arg2: string, arg3: string, arg4: number, arg5: number, arg6: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addOverlockRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOverlockRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addProductionRecord(arg0: string, arg1: string, arg2: string, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProductionRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProductionRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async addTailorRecord(arg0: string, arg1: string, arg2: string, arg3: number, arg4: number, arg5: number, arg6: string, arg7: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTailorRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTailorRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async deleteAdditionalWorkRecord(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAdditionalWorkRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAdditionalWorkRecord(arg0);
            return result;
        }
    }
    async deleteDispatchRecord(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDispatchRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDispatchRecord(arg0);
            return result;
        }
    }
    async deleteItemMaster(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteItemMaster(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteItemMaster(arg0);
            return result;
        }
    }
    async deleteOverlockRecord(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOverlockRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOverlockRecord(arg0);
            return result;
        }
    }
    async deleteProductionRecord(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProductionRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProductionRecord(arg0);
            return result;
        }
    }
    async deleteTailorRecord(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTailorRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTailorRecord(arg0);
            return result;
        }
    }
    async getAdditionalWorkByArticle(arg0: string): Promise<Array<AdditionalWorkRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdditionalWorkByArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdditionalWorkByArticle(arg0);
            return result;
        }
    }
    async getAdditionalWorkQtyByColorSize(arg0: string, arg1: string, arg2: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdditionalWorkQtyByColorSize(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdditionalWorkQtyByColorSize(arg0, arg1, arg2);
            return result;
        }
    }
    async getAdditionalWorkRecords(): Promise<Array<AdditionalWorkRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdditionalWorkRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdditionalWorkRecords();
            return result;
        }
    }
    async getArticleRemainingQty(arg0: string): Promise<number | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticleRemainingQty(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticleRemainingQty(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArticleReport(): Promise<Array<[string, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticleReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticleReport();
            return result;
        }
    }
    async getAvailableStock(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableStock(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableStock(arg0);
            return result;
        }
    }
    async getDispatchRecords(): Promise<Array<DispatchRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDispatchRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDispatchRecords();
            return result;
        }
    }
    async getDispatchedQtyByArticle(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getDispatchedQtyByArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDispatchedQtyByArticle(arg0);
            return result;
        }
    }
    async getFabricConsumptionReport(): Promise<Array<FabricConsumptionReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFabricConsumptionReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFabricConsumptionReport();
            return result;
        }
    }
    async getFabricPerPiece(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getFabricPerPiece(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFabricPerPiece(arg0);
            return result;
        }
    }
    async getFinishedStockSummary(): Promise<Array<FinishedStockSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinishedStockSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinishedStockSummary();
            return result;
        }
    }
    async getItemMasterByArticle(arg0: string): Promise<ItemMaster | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getItemMasterByArticle(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItemMasterByArticle(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getItemMasters(): Promise<Array<ItemMaster>> {
        if (this.processError) {
            try {
                const result = await this.actor.getItemMasters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItemMasters();
            return result;
        }
    }
    async getMasterNames(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMasterNames();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMasterNames();
            return result;
        }
    }
    async getMasterReport(): Promise<Array<[string, number, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMasterReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMasterReport();
            return result;
        }
    }
    async getOverlockRecords(): Promise<Array<OverlockRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOverlockRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOverlockRecords();
            return result;
        }
    }
    async getOverlockReport(): Promise<Array<[string, number, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOverlockReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOverlockReport();
            return result;
        }
    }
    async getPaymentSummary(): Promise<Array<[string, number, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentSummary();
            return result;
        }
    }
    async getProductionMismatches(): Promise<Array<ProductionMismatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductionMismatches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductionMismatches();
            return result;
        }
    }
    async getProductionRecords(): Promise<Array<ProductionRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductionRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductionRecords();
            return result;
        }
    }
    async getStitchedQtyByColorSize(arg0: string, arg1: string, arg2: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getStitchedQtyByColorSize(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStitchedQtyByColorSize(arg0, arg1, arg2);
            return result;
        }
    }
    async getTailorQtyByArticle(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTailorQtyByArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTailorQtyByArticle(arg0);
            return result;
        }
    }
    async getTailorRecords(): Promise<Array<TailorRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTailorRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTailorRecords();
            return result;
        }
    }
    async getTailorReport(): Promise<Array<[string, number, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTailorReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTailorReport();
            return result;
        }
    }
    async setFabricPerPiece(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setFabricPerPiece(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFabricPerPiece(arg0, arg1);
            return result;
        }
    }
    async updateAdditionalWorkRecord(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: number, arg6: number, arg7: string, arg8: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdditionalWorkRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdditionalWorkRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async updateDispatchRecord(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: number, arg5: number, arg6: number, arg7: string, arg8: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDispatchRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDispatchRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async updateItemMaster(arg0: bigint, arg1: string, arg2: number, arg3: string, arg4: boolean, arg5: string, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: number, arg12: number, arg13: number, arg14: number, arg15: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateItemMaster(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateItemMaster(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15);
            return result;
        }
    }
    async updateOverlockRecord(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: number, arg6: number, arg7: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOverlockRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOverlockRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateProductionRecord(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProductionRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProductionRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async updateTailorRecord(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: number, arg5: number, arg6: number, arg7: string, arg8: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTailorRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTailorRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ItemMaster]): ItemMaster | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
